In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('dirty_cafe_sales.csv')

In [4]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [6]:
print("shape:", df.shape)
print("\nData types:\n", df.dtypes)
print("\n Null values per column:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

shape: (10000, 8)

Data types:
 Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

 Null values per column:
 Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

Duplicate rows: 0

In [7]:
for col in df.columns:
    print(f"\n{col} unique values (sample):")
    print(df[col].unique())

Transaction ID unique values (sample):
<StringArray>
['TXN_1961373', 'TXN_4977031', 'TXN_4271903', 'TXN_7034554', 'TXN_3160411',
 'TXN_2602893', 'TXN_4433211', 'TXN_6699534', 'TXN_4717867', 'TXN_2064365',
 ...
 'TXN_1538510', 'TXN_3897619', 'TXN_2739140', 'TXN_4766549', 'TXN_7851634',
 'TXN_7672686', 'TXN_9659401', 'TXN_5255387', 'TXN_7695629', 'TXN_6170729']
Length: 10000, dtype: str

Item unique values (sample):
<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

Quantity unique values (sample):
<StringArray>
['2', '4', '5', '3', '1', 'ERROR', 'UNKNOWN', nan]
Length: 8, dtype: str

Price Per Unit unique values (sample):
<StringArray>
['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN']
Length: 9, dtype: str

Total Spent unique values (sample):
<StringArray>
[    '4.0',    '12.0',   'ERROR',    '10.0',    '20.0',     '9.0',    '16.0',
    '15.0',    '25.0',     '8.0',     '5.0',     '3.0',     '6.0',       nan,
 'UNKNOWN',     '2.0',     '1.0',     '7.5',     '4.5',     '1.5']
Length: 20, dtype: str

Payment Method unique values (sample):
<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

Location unique values (sample):
<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

Transaction Date unique values (sample):
<StringArray>
['2023-09-08', '2023-05-16', '2023-07-19', '2023-04-27', '2023-06-11',
 '2023-03-31', '2023-10-06', '2023-10-28', '2023-07-28', '2023-12-31',
 ...
 '2023-08-01', '2023-01-20', '2023-11-11', '2023-02-13', '2023-07-30',
 '2023-02-17', '2023-05-20', '2023-11-05', '2023-03-27', '2023-07-03']
Length: 368, dtype: str

## Data Quality Report

The dataset has 10,000 rows and 8 columns. Every column is currently stored as 
text (object type), even ones that should be numbers like Quantity, Price Per 
Unit, and Total Spent - this needs fixing.

Several columns have missing values: Item (333), Quantity (138), Price Per Unit 
(179), Total Spent (173), Payment Method (2579), Location (3265), and 
Transaction Date (159). No duplicate rows were found.

On top of that, columns like Item, Quantity, and Price Per Unit contain invalid 
placeholder values like "ERROR" and "UNKNOWN" mixed in with real data - these 
also need to be treated as missing values before any real cleaning can happen.

In [9]:
df.replace(['ERROR','UNKNOWN'],np.nan,inplace=True)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [10]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

## Cleaning ERROR/UNKNOWN Values

After converting "ERROR" and "UNKNOWN" placeholder text into actual missing 
values (NaN), the number of nulls in every column went up quite a bit. For 
example, Item nulls jumped from 333 to 969, and Location from 3265 to 3961. 
This confirms these placeholder values were hiding a lot more missing data 
than it first looked like.

In [12]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')

df.dtypes

Transaction ID                 str
Item                           str
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
dtype: object

## Fixing Data Types

Quantity, Price Per Unit, and Total Spent are now proper numbers (float64) 
instead of text, and Transaction Date is now in proper datetime format. This 
was necessary because these columns need to be numeric/date types to do any 
real calculations or time-based analysis later.

In [13]:
df['Item'] = df['Item'].fillna('Unknown')
df['Payment Method'] = df['Payment Method'].fillna('Unknown')
df['Location'] = df['Location'].fillna('Unknown')

df.isnull().sum()

Transaction ID        0
Item                  0
Quantity            479
Price Per Unit      533
Total Spent         502
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

## Handling Missing Text Values

For Item, Payment Method, and Location, missing values were filled with 
"Unknown" instead of deleting those rows. Deleting them would mean losing 
otherwise valid transaction data (like quantity and price), so filling with 
a placeholder keeps the data usable while still being honest that we don't 
know the actual value.

In [14]:
mask1 = df['Total Spent'].isna() & df['Quantity'].notna() & df['Price Per Unit'].notna()
df.loc[mask1, 'Total Spent'] = df.loc[mask1, 'Quantity'] * df.loc[mask1, 'Price Per Unit']

mask2 = df['Quantity'].isna() & df['Total Spent'].notna() & df['Price Per Unit'].notna()
df.loc[mask2, 'Quantity'] = df.loc[mask2, 'Total Spent'] / df.loc[mask2, 'Price Per Unit']

mask3 = df['Price Per Unit'].isna() & df['Total Spent'].notna() & df['Quantity'].notna()
df.loc[mask3, 'Price Per Unit'] = df.loc[mask3, 'Total Spent'] / df.loc[mask3, 'Quantity']

df.isnull().sum()

Transaction ID        0
Item                  0
Quantity             38
Price Per Unit       38
Total Spent          40
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

## Calculating Missing Values from Related Columns

Since Total Spent = Quantity × Price Per Unit, missing values in any one of 
these three columns could often be calculated using the other two. This 
brought down missing values significantly - Quantity and Price Per Unit 
dropped from 479/533 to just 38 each, and Total Spent dropped from 502 to 40. 
This is a much better approach than deleting rows or guessing, since it uses 
actual math instead of assumptions.

In [15]:
before_rows = df.shape[0]

df = df.dropna(subset=['Quantity', 'Price Per Unit', 'Total Spent'], how='all')

after_rows = df.shape[0]
print(f"Rows before: {before_rows}, Rows after: {after_rows}, Rows dropped: {before_rows - after_rows}")

df.isnull().sum()

Rows before: 10000, Rows after: 10000, Rows dropped: 0

Transaction ID        0
Item                  0
Quantity             38
Price Per Unit       38
Total Spent          40
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [16]:
before_rows = df.shape[0]

df = df.dropna(subset=['Transaction Date'])

after_rows = df.shape[0]
print(f"Rows before: {before_rows}, Rows after: {after_rows}, Rows dropped: {before_rows - after_rows}")

df.isnull().sum()

Rows before: 10000, Rows after: 9540, Rows dropped: 460

Transaction ID       0
Item                 0
Quantity            36
Price Per Unit      35
Total Spent         39
Payment Method       0
Location             0
Transaction Date     0
dtype: int64

## Dropping Rows with Missing Dates

Transaction Date had 460 missing values with no way to calculate or guess the 
correct date, so those rows were removed entirely. This brought the dataset 
down from 10,000 to 9,540 rows. Some of these dropped rows also happened to 
have missing Quantity, Price, or Total Spent values, which is why those 
counts dropped slightly too (from 38/38/40 to 36/35/39).

In [17]:
before_rows = df.shape[0]

df = df.dropna(subset=['Quantity', 'Price Per Unit', 'Total Spent'], how='all')

after_rows = df.shape[0]
print(f"Rows before: {before_rows}, Rows after: {after_rows}, Rows dropped: {before_rows - after_rows}")

df.isnull().sum()

Rows before: 9540, Rows after: 9540, Rows dropped: 0

Transaction ID       0
Item                 0
Quantity            36
Price Per Unit      35
Total Spent         39
Payment Method       0
Location             0
Transaction Date     0
dtype: int64

In [18]:
before_rows = df.shape[0]

df = df.dropna(subset=['Quantity', 'Price Per Unit', 'Total Spent'], how='any')

after_rows = df.shape[0]
print(f"Rows before: {before_rows}, Rows after: {after_rows}, Rows dropped: {before_rows - after_rows}")

df.isnull().sum()

Rows before: 9540, Rows after: 9485, Rows dropped: 55

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

## Removing Remaining Incomplete Rows

After all the calculations, 55 rows still had missing values in Quantity, 
Price Per Unit, or Total Spent (likely because 2 out of the 3 values were 
missing together, making calculation impossible). These rows were dropped, 
bringing the dataset from 9,540 to 9,485 rows. At this point, every column 
in the dataset has zero missing values.

In [19]:
duplicate_count = df.duplicated().sum()
print(f"Duplicate rows before: {duplicate_count}")

df = df.drop_duplicates()
print(f"Shape after removing duplicates: {df.shape}")

Duplicate rows before: 0
Shape after removing duplicates: (9485, 8)

## Duplicate Check

Rechecked for duplicate rows after cleaning, and found none. This confirms 
the dataset didn't have any duplicate transactions to begin with, so no 
rows were removed in this step.

In [20]:
print("Payment Method values:",df['Payment Method'].unique())
print("\nLocation values:", df['Location'].unique())
print("\nItem values:", df['Item'].unique())

Payment Method values: <StringArray>
['Credit Card', 'Cash', 'Unknown', 'Digital Wallet']
Length: 4, dtype: str

Location values: <StringArray>
['Takeaway', 'In-store', 'Unknown']
Length: 3, dtype: str

Item values: <StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'Unknown',
 'Sandwich',    'Juice',      'Tea']
Length: 9, dtype: str

## Standardisation Check

Checked Payment Method, Location, and Item columns for inconsistent 
formatting (like mixed casing or spelling variations). All values across 
these columns were already consistent - no case mismatches or duplicate 
categories with different spellings were found, so no standardisation was 
needed here.

In [21]:
for col in ['Quantity', 'Price Per Unit', 'Total Spent']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"{col}: {len(outliers)} outliers found (bounds: {lower_bound:.2f} to {upper_bound:.2f})")

Quantity: 0 outliers found (bounds: -1.00 to 7.00)
Price Per Unit: 0 outliers found (bounds: -1.00 to 7.00)
Total Spent: 258 outliers found (bounds: -8.00 to 24.00)

## Outlier Detection

Using the IQR method, Quantity and Price Per Unit showed no outliers - their 
values stay within a normal, tight range. Total Spent, however, showed 258 
outliers with the upper bound at just ₹24.

After looking closer, this makes sense: Total Spent is simply Quantity × 
Price Per Unit, so when a customer buys a higher quantity of a slightly 
pricier item, the total naturally goes above the "normal" range. Since 
Quantity and Price Per Unit are individually fine, these aren't data errors - 
they're just larger, valid transactions (like bulk or group orders). 
Decision: these outliers were retained rather than removed or capped, since 
removing them would mean deleting real, legitimate sales data.

In [22]:
summary = pd.DataFrame({
    'Metric': ['Total Rows', 'Null Values (Total)', 'Duplicate Rows', 'Correct Data Types'],
    'Before Cleaning': [10000, 8871, 0, 'No (all columns were text)'],
    'After Cleaning': [df.shape[0], df.isnull().sum().sum(), df.duplicated().sum(), 'Yes (numbers/dates fixed)']
})

summary

                Metric             Before Cleaning             After Cleaning
0           Total Rows                       10000                       9485
1  Null Values (Total)                        8871                          0
2       Duplicate Rows                           0                          0
3   Correct Data Types  No (all columns were text)  Yes (numbers/dates fixed)

In [23]:
df.to_csv('cleaned_cafe_sales.csv', index=False)
print("Cleaned dataset saved as 'cleaned_cafe_sales.csv'")

Cleaned dataset saved as 'cleaned_cafe_sales.csv'

## Conclusion

This dataset went through a thorough cleaning process:

1. Converted "ERROR" and "UNKNOWN" placeholder text into proper missing 
values (NaN), which revealed much more missing data than initially visible.

2. Fixed data types - Quantity, Price Per Unit, and Total Spent were 
converted from text to numbers, and Transaction Date to a proper date format.

3. Handled missing values with different strategies per column: text 
columns (Item, Payment Method, Location) were filled with "Unknown", while 
Quantity/Price/Total Spent were calculated from each other where possible, 
and remaining unrecoverable rows were dropped along with rows missing dates.

4. Checked for duplicates and formatting inconsistencies - none were found.

5. Detected outliers in Total Spent using the IQR method, but chose to 
retain them since they represent valid larger transactions rather than 
data errors.

The dataset shrank from 10,000 to 9,485 rows (about 5% data loss), but is 
now fully clean with zero missing values and correct data types, ready for 
further analysis.